services:
  redis:
    image: redis:latest
    container_name: my_redis_container
    ports:
      - "6379:6379"
    volumes:
      - redisdb-data:/data
    networks:
      - redis-network

volumes:
  redis-data:

networks:
  redis-network: